### ISSUE TITLE
タグ付け

### ISSUE THREAD

**Issue by d-junk** [Uchiborii/Clinic-HP#5]
・h1タグがない。セオリーとしては病院名につける。今回はロゴに画像を使っているので画像のalt属性に病院名を入れて、h1タグで括ってあげる
・当院のご紹介とアクセスで、見出しタグの付け方がおかしい。アウトラインの階層について思い出してください。
・診療時間にtableタグを使っている中で、captionタグの使い方が間違っている。captionタグはテーブルの内容を説明する見出しの意味合いで使用します。
・footerタグはmainタグの外側に出すべき
・div#headerの中にheaderタグがあり、記述ルールが統一されていない。header#headerにして揃えるべき

**Comment by Uchiborii** [comment]
- [x] h1タグがない。セオリーとしては病院名につける。今回はロゴに画像を使っているので画像のalt属性に病院名を入れて、h1タグで括ってあげる

- [x] 当院のご紹介とアクセスで、見出しタグの付け方がおかしい。アウトラインの階層について思い出してください。

- [x] 診療時間にtableタグを使っている中で、captionタグの使い方が間違っている。captionタグはテーブルの内容を説明する見出しの意味合いで使用します。

- [x] footerタグはmainタグの外側に出すべき

- [x] div#headerの中にheaderタグがあり、記述ルールが統一されていない。header#headerにして揃えるべき
